version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          app-dir: ~/project/DjangoWebProject
      - run:
          name: Test
          working-dir: ~/project/DjangoWebProject
          command: |
            python --version
workflows:
  main:
    jobs:
      - build