# Generated by Django 2.2.27 on 2022-04-03 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entertime', models.DateTimeField()),
                ('score', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
            options={
                'db_table': 'dra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ireadymath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entertime', models.DateTimeField()),
                ('score', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
            options={
                'db_table': 'ireadymath',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ireadyreading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entertime', models.DateTimeField()),
                ('score', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
            options={
                'db_table': 'ireadyreading',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.DecimalField(decimal_places=0, max_digits=8, primary_key=True, serialize=False)),
                ('first_name', models.TextField(max_length=25)),
                ('last_name', models.TextField(max_length=25)),
                ('truancy', models.DecimalField(decimal_places=0, max_digits=3)),
                ('composite_score', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('first_name', models.TextField(max_length=25)),
                ('last_name', models.TextField(max_length=25)),
            ],
            options={
                'db_table': 'teacher',
                'managed': False,
            },
        ),
    ]
